/**
 * Client-side document export — PDF via html2pdf.js, DOCX via docx library.
 * Both use dynamic imports so they're only loaded when the user clicks download.
 */

// ── PDF Export ──
// Premium PDF rendering with:
//   • Cover page when content > 800 words (logo + title + accent rule, full A4 page)
//   • Inline title for short content
//   • Running header (small ConvoiaMark logo + title) on every content page
//   • Running footer (title · ConvoiaAI · Page X of Y) on every page
//   • Clean code blocks (dark bg, no UI header bar — stripped via data-pdf-skip)
//   • Consistent typography hierarchy + section dividers + page-break rules

const WORD_COUNT_COVER_THRESHOLD = 800
const ACCENT = '#7C3AED'           // brand purple
const ACCENT_RGB: [number, number, number] = [124, 58, 237]
const ACCENT_FAINT_RGB: [number, number, number] = [222, 206, 250]  // 25% accent on white

function sanitizeFilename(s: string): string {
  return s.replace(/[^a-zA-Z0-9\s-]/g, '').trim().replace(/\s+/g, '-') || 'document'
}

function truncate(s: string, n: number): string {
  return s.length > n ? s.slice(0, n - 1).trimEnd() + '…' : s
}

function countWords(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length
}

// Build the full A4 cover page (logo + title + date + accent rule).
function buildCoverPage(title: string, dateStr: string): HTMLElement {
  const cover = document.createElement('div')
  cover.style.cssText = `
    page-break-after: always;
    break-after: page;
    height: 257mm;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    padding: 0 20mm;
  `
  cover.innerHTML = `
    <svg viewBox="0 0 24 24" width="72" height="72" style="margin-bottom: 48px;" xmlns="http://www.w3.org/2000/svg">
      <g stroke="${ACCENT}" stroke-width="0.6" opacity="0.25" fill="none">
        <line x1="6" y1="6" x2="18" y2="6" />
        <line x1="6" y1="6" x2="6" y2="18" />
        <line x1="18" y1="6" x2="18" y2="18" />
        <line x1="6" y1="18" x2="18" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
        <line x1="18" y1="6" x2="6" y2="18" />
      </g>
      <g fill="${ACCENT}">
        <circle cx="6" cy="6" r="1.8" />
        <circle cx="18" cy="6" r="1.8" />
        <circle cx="18" cy="18" r="1.8" />
        <circle cx="6" cy="18" r="1.8" />
      </g>
    </svg>
    <h1 style="font-family: Georgia, 'Times New Roman', serif; font-size: 36pt; font-weight: 700; color: #1a1a1a; margin: 0 0 24px; line-height: 1.2; letter-spacing: -0.5px;">${escapeHtml(title)}</h1>
    <p style="font-size: 10pt; color: #6b7280; margin: 0 0 32px; letter-spacing: 1.5px; text-transform: uppercase; font-family: Georgia, serif;">Generated by ConvoiaAI &middot; ${escapeHtml(dateStr)}</p>
    <div style="width: 80px; height: 2px; background: ${ACCENT};"></div>
  `
  return cover
}

// Inline title block for short docs (no cover page).
function buildInlineTitle(title: string, dateStr: string): HTMLElement {
  const block = document.createElement('div')
  block.style.cssText = 'text-align: center; margin: 0 0 36px; padding-bottom: 22px; border-bottom: 2px solid ' + ACCENT + ';'
  block.innerHTML = `
    <h1 style="font-size: 24pt; color: #1a1a1a; margin: 0 0 8px; font-weight: 700; line-height: 1.25;">${escapeHtml(title)}</h1>
    <p style="font-size: 10pt; color: #6b7280; margin: 0; letter-spacing: 0.5px;">Generated by ConvoiaAI &middot; ${escapeHtml(dateStr)}</p>
  `
  return block
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

// Re-style cloned content for premium print appearance.
// Order matters: we don't blanket-override so syntax-highlighting tokens survive.
function applyPrintStyles(clone: HTMLElement): void {
  // Headings — clear hierarchy, no orphan
  clone.querySelectorAll('h1').forEach((el) => {
    const e = el as HTMLElement
    e.style.fontSize = '22pt'
    e.style.fontWeight = '700'
    e.style.color = '#111'
    e.style.margin = '32px 0 16px'
    e.style.paddingBottom = '6px'
    e.style.borderBottom = '1px solid #e5e7eb'
    e.style.lineHeight = '1.3'
    e.style.pageBreakAfter = 'avoid'
    e.style.breakAfter = 'avoid'
  })
  clone.querySelectorAll('h2').forEach((el) => {
    const e = el as HTMLElement
    e.style.fontSize = '17pt'
    e.style.fontWeight = '600'
    e.style.color = '#111'
    e.style.margin = '28px 0 12px'
    e.style.lineHeight = '1.35'
    e.style.pageBreakAfter = 'avoid'
    e.style.breakAfter = 'avoid'
  })
  clone.querySelectorAll('h3').forEach((el) => {
    const e = el as HTMLElement
    e.style.fontSize = '14pt'
    e.style.fontWeight = '600'
    e.style.color = '#111'
    e.style.margin = '22px 0 10px'
    e.style.lineHeight = '1.4'
    e.style.pageBreakAfter = 'avoid'
    e.style.breakAfter = 'avoid'
  })
  clone.querySelectorAll('h4, h5, h6').forEach((el) => {
    const e = el as HTMLElement
    e.style.fontSize = '12pt'
    e.style.fontWeight = '600'
    e.style.color = '#111'
    e.style.margin = '18px 0 8px'
    e.style.pageBreakAfter = 'avoid'
    e.style.breakAfter = 'avoid'
  })

  // Body paragraphs — readable density
  clone.querySelectorAll('p').forEach((el) => {
    const e = el as HTMLElement
    e.style.fontSize = '11pt'
    e.style.lineHeight = '1.7'
    e.style.color = '#1f2937'
    e.style.margin = '0 0 14px'
  })

  // Lists
  clone.querySelectorAll('ul, ol').forEach((el) => {
    const e = el as HTMLElement
    e.style.margin = '12px 0 16px'
    e.style.paddingLeft = '24px'
  })
  clone.querySelectorAll('li').forEach((el) => {
    const e = el as HTMLElement
    e.style.fontSize = '11pt'
    e.style.lineHeight = '1.65'
    e.style.color = '#1f2937'
    e.style.margin = '4px 0'
  })

  // Blockquotes — pull-quote treatment
  clone.querySelectorAll('blockquote').forEach((el) => {
    const e = el as HTMLElement
    e.style.borderLeft = `3px solid ${ACCENT}`
    e.style.paddingLeft = '18px'
    e.style.margin = '20px 0'
    e.style.color = '#4b5563'
    e.style.fontStyle = 'italic'
    e.style.fontSize = '11.5pt'
    e.style.lineHeight = '1.65'
    e.style.pageBreakInside = 'avoid'
    e.style.breakInside = 'avoid'
  })

  // Section dividers — consistent rhythm
  clone.querySelectorAll('hr').forEach((el) => {
    const e = el as HTMLElement
    e.style.border = 'none'
    e.style.borderTop = '1px solid #e5e7eb'
    e.style.margin = '32px 0'
    e.style.height = '0'
  })

  // Code blocks — dark, clean, syntax-highlighting preserved
  clone.querySelectorAll('pre').forEach((el) => {
    const e = el as HTMLElement
    e.style.background = '#1a1d23'
    e.style.color = '#e6edf3'
    e.style.borderRadius = '8px'
    e.style.padding = '16px 18px'
    e.style.margin = '16px 0'
    e.style.border = '1px solid #2a2d33'
    e.style.fontFamily = "'Fira Code', 'Consolas', monospace"
    e.style.fontSize = '10pt'
    e.style.lineHeight = '1.6'
    e.style.pageBreakInside = 'avoid'
    e.style.breakInside = 'avoid'
    e.style.overflow = 'hidden'
    e.style.whiteSpace = 'pre-wrap'
    e.style.wordBreak = 'break-word'
  })
  // Inside <pre>: keep transparent so oneDark token colors shine through
  clone.querySelectorAll('pre code, pre code *').forEach((el) => {
    const e = el as HTMLElement
    e.style.background = 'transparent'
    if (!e.style.color) e.style.color = '#e6edf3'
  })
  // Inline code — light pill on light bg
  clone.querySelectorAll('code').forEach((el) => {
    if ((el.parentElement?.tagName || '') === 'PRE') return
    const e = el as HTMLElement
    e.style.background = '#f3f4f6'
    e.style.color = ACCENT
    e.style.padding = '2px 6px'
    e.style.borderRadius = '4px'
    e.style.fontFamily = "'Fira Code', 'Consolas', monospace"
    e.style.fontSize = '10pt'
    e.style.border = '1px solid #e5e7eb'
  })

  // Tables — keep together, clean borders
  clone.querySelectorAll('table').forEach((el) => {
    const e = el as HTMLElement
    e.style.borderCollapse = 'collapse'
    e.style.width = '100%'
    e.style.margin = '16px 0'
    e.style.fontSize = '10pt'
    e.style.pageBreakInside = 'avoid'
    e.style.breakInside = 'avoid'
  })
  clone.querySelectorAll('th, td').forEach((el) => {
    const e = el as HTMLElement
    e.style.border = '1px solid #d1d5db'
    e.style.padding = '8px 12px'
    e.style.textAlign = 'left'
    e.style.color = '#1f2937'
    if (el.tagName === 'TH') {
      e.style.background = '#f9fafb'
      e.style.fontWeight = '600'
    }
  })

  // Strong/em — preserve emphasis
  clone.querySelectorAll('strong, b').forEach((el) => {
    (el as HTMLElement).style.fontWeight = '600'
  })
  clone.querySelectorAll('em, i').forEach((el) => {
    (el as HTMLElement).style.fontStyle = 'italic'
  })

  // Links — accent-colored, preserved underline
  clone.querySelectorAll('a').forEach((el) => {
    const e = el as HTMLElement
    e.style.color = ACCENT
    e.style.textDecoration = 'underline'
  })

  // Images — fit within page, don't break across
  clone.querySelectorAll('img').forEach((el) => {
    const e = el as HTMLElement
    e.style.maxWidth = '100%'
    e.style.height = 'auto'
    e.style.pageBreakInside = 'avoid'
    e.style.breakInside = 'avoid'
    e.style.borderRadius = '4px'
  })
}

// Draw the ConvoiaMark logo (4 nodes + 6 connecting lines) directly via jsPDF
// vector primitives. No image-loading, crisp at any scale.
function drawConvoiaMark(pdf: any, x: number, y: number, size: number): void {
  const s = size / 24  // SVG viewBox is 24×24
  // 6 connecting lines — pre-computed lighter purple (no GState dependency)
  pdf.setDrawColor(ACCENT_FAINT_RGB[0], ACCENT_FAINT_RGB[1], ACCENT_FAINT_RGB[2])
  pdf.setLineWidth(0.15 * s)
  pdf.line(x + 6 * s, y + 6 * s, x + 18 * s, y + 6 * s)
  pdf.line(x + 6 * s, y + 6 * s, x + 6 * s, y + 18 * s)
  pdf.line(x + 18 * s, y + 6 * s, x + 18 * s, y + 18 * s)
  pdf.line(x + 6 * s, y + 18 * s, x + 18 * s, y + 18 * s)
  pdf.line(x + 6 * s, y + 6 * s, x + 18 * s, y + 18 * s)
  pdf.line(x + 18 * s, y + 6 * s, x + 6 * s, y + 18 * s)
  // 4 nodes — full accent
  pdf.setFillColor(ACCENT_RGB[0], ACCENT_RGB[1], ACCENT_RGB[2])
  pdf.circle(x + 6 * s, y + 6 * s, 0.45 * s, 'F')
  pdf.circle(x + 18 * s, y + 6 * s, 0.45 * s, 'F')
  pdf.circle(x + 18 * s, y + 18 * s, 0.45 * s, 'F')
  pdf.circle(x + 6 * s, y + 18 * s, 0.45 * s, 'F')
}

// Walk every page after PDF generation and add running header + footer.
// Cover page (when present) gets footer only.
function drawRunningHeadersFooters(pdf: any, title: string, hasCover: boolean): void {
  const totalPages = pdf.internal.getNumberOfPages()
  const pageW = pdf.internal.pageSize.getWidth()
  const pageH = pdf.internal.pageSize.getHeight()
  const titleHeader = truncate(title, 60)
  const titleFooter = truncate(title, 50)

  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i)
    const isCoverPage = hasCover && i === 1

    // ── Header (skip on cover page) ──
    if (!isCoverPage) {
      drawConvoiaMark(pdf, 15, 8, 5)  // top-left, 5mm
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(8)
      pdf.setTextColor(120)
      pdf.text(titleHeader, pageW - 15, 11, { align: 'right' })
      pdf.setDrawColor(220)
      pdf.setLineWidth(0.1)
      pdf.line(15, 14, pageW - 15, 14)
    }

    // ── Footer (every page) ──
    pdf.setDrawColor(220)
    pdf.setLineWidth(0.1)
    pdf.line(15, pageH - 12, pageW - 15, pageH - 12)
    pdf.setFont('helvetica', 'normal')
    pdf.setFontSize(7.5)
    pdf.setTextColor(140)
    const footerText = `${titleFooter} · ConvoiaAI · Page ${i} of ${totalPages}`
    pdf.text(footerText, pageW / 2, pageH - 8, { align: 'center' })
  }
}

export async function exportToPdf(contentElement: HTMLElement, title: string): Promise<void> {
  const html2pdf = (await import('html2pdf.js')).default

  // Decide cover-page eligibility BEFORE cloning (textContent on source is faster)
  const sourceText = contentElement.textContent || ''
  const wordCount = countWords(sourceText)
  const hasCover = wordCount > WORD_COUNT_COVER_THRESHOLD
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  // Clone source, then strip any element marked as PDF-skip (e.g. CodeBlock UI header bar).
  // This MUST happen before applyPrintStyles so styled elements aren't computed for nothing.
  const clone = contentElement.cloneNode(true) as HTMLElement
  clone.querySelectorAll('[data-pdf-skip="true"]').forEach((el) => el.remove())

  // Re-style for print
  applyPrintStyles(clone)

  // Build wrapper
  const wrapper = document.createElement('div')
  wrapper.style.cssText = `
    background: white;
    color: #1a1a1a;
    font-family: Georgia, 'Times New Roman', serif;
    font-size: 11pt;
    line-height: 1.7;
    padding: 0;
    margin: 0 auto;
    max-width: 170mm;
    orphans: 3;
    widows: 3;
  `

  if (hasCover) {
    wrapper.appendChild(buildCoverPage(title, dateStr))
  } else {
    wrapper.appendChild(buildInlineTitle(title, dateStr))
  }
  wrapper.appendChild(clone)

  const opt = {
    margin: [20, 18, 20, 18] as [number, number, number, number],  // top/right/bottom/left mm — extra room for header+footer
    filename: sanitizeFilename(title) + '.pdf',
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true, backgroundColor: '#ffffff' },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' as const, compress: true },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
  }

  // Staged execution so we can post-process the jsPDF document with running headers/footers/page numbers.
  const worker = html2pdf().set(opt).from(wrapper)
  await worker.toContainer()
  await worker.toCanvas()
  await worker.toImg()
  await worker.toPdf()
  const pdf: any = worker.get('pdf')

  drawRunningHeadersFooters(pdf, title, hasCover)

  await worker.save()
}

// ── DOCX Export ──
export async function exportToDocx(markdownContent: string, title: string): Promise<void> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, Table, TableRow, TableCell,
    WidthType, ShadingType,
  } = await import('docx')
  const { saveAs } = await import('file-saver')

  const lines = markdownContent.split('\n')
  const children: any[] = []
  let inCodeBlock = false
  let codeLines: string[] = []
  let inTable = false
  let tableRows: string[][] = []

  function flushCode() {
    if (codeLines.length === 0) return
    children.push(
      new Paragraph({
        children: [new TextRun({
          text: codeLines.join('\n'),
          font: 'Consolas',
          size: 18,
          color: '333333',
        })],
        shading: { type: ShadingType.SOLID, color: 'F5F5F5', fill: 'F5F5F5' },
        spacing: { before: 120, after: 120 },
        border: {
          top: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          left: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          right: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
        },
      })
    )
    codeLines = []
  }

  function flushTable() {
    if (tableRows.length === 0) return
    const rows = tableRows.map((cells, rowIdx) =>
      new TableRow({
        children: cells.map(cell =>
          new TableCell({
            children: [new Paragraph({
              children: [new TextRun({ text: cell.trim(), bold: rowIdx === 0, size: 20, font: 'Calibri' })],
              spacing: { before: 40, after: 40 },
            })],
            width: { size: Math.floor(100 / cells.length), type: WidthType.PERCENTAGE },
            shading: rowIdx === 0 ? { type: ShadingType.SOLID, color: 'F0EFFF', fill: 'F0EFFF' } : undefined,
          })
        ),
      })
    )
    children.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }))
    tableRows = []
  }

  // Parse inline bold/italic
  function parseInline(text: string): any[] {
    const runs: any[] = []
    const regex = /(\*\*\*(.+?)\*\*\*|\*\*(.+?)\*\*|\*(.+?)\*|`(.+?)`|([^*`]+))/g
    let match
    while ((match = regex.exec(text)) !== null) {
      if (match[2]) runs.push(new TextRun({ text: match[2], bold: true, italics: true, size: 22, font: 'Calibri' }))
      else if (match[3]) runs.push(new TextRun({ text: match[3], bold: true, size: 22, font: 'Calibri' }))
      else if (match[4]) runs.push(new TextRun({ text: match[4], italics: true, size: 22, font: 'Calibri' }))
      else if (match[5]) runs.push(new TextRun({ text: match[5], font: 'Consolas', size: 20, color: '7C3AED' }))
      else if (match[6]) runs.push(new TextRun({ text: match[6], size: 22, font: 'Calibri' }))
    }
    return runs.length ? runs : [new TextRun({ text, size: 22, font: 'Calibri' })]
  }

  for (const line of lines) {
    // Code block toggle
    if (line.trim().startsWith('```')) {
      if (inCodeBlock) { inCodeBlock = false; flushCode() }
      else { inCodeBlock = true; flushTable() }
      continue
    }
    if (inCodeBlock) { codeLines.push(line); continue }

    // Table rows
    if (line.trim().startsWith('|') && line.trim().endsWith('|')) {
      if (!inTable) inTable = true
      const cells = line.split('|').filter(c => c.trim()).map(c => c.trim())
      // Skip separator rows (|---|---|)
      if (cells.every(c => /^[-:]+$/.test(c))) continue
      tableRows.push(cells)
      continue
    } else if (inTable) {
      inTable = false
      flushTable()
    }

    // Headings
    const h1 = line.match(/^#\s+(.+)/)
    const h2 = line.match(/^##\s+(.+)/)
    const h3 = line.match(/^###\s+(.+)/)
    if (h1) { children.push(new Paragraph({ children: parseInline(h1[1]), heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 120 } })); continue }
    if (h2) { children.push(new Paragraph({ children: parseInline(h2[1]), heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 100 } })); continue }
    if (h3) { children.push(new Paragraph({ children: parseInline(h3[1]), heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 } })); continue }

    // Bullet list
    const bullet = line.match(/^\s*[-*]\s+(.+)/)
    if (bullet) { children.push(new Paragraph({ children: parseInline(bullet[1]), bullet: { level: 0 }, spacing: { before: 40, after: 40 } })); continue }

    // Numbered list
    const numbered = line.match(/^\s*\d+\.\s+(.+)/)
    if (numbered) { children.push(new Paragraph({ children: parseInline(numbered[1]), numbering: { reference: 'default-numbering', level: 0 }, spacing: { before: 40, after: 40 } })); continue }

    // Blockquote
    const quote = line.match(/^>\s*(.+)/)
    if (quote) {
      children.push(new Paragraph({
        children: [new TextRun({ text: quote[1], italics: true, size: 22, color: '555555', font: 'Calibri' })],
        indent: { left: 720 },
        border: { left: { style: BorderStyle.SINGLE, size: 6, color: '7C3AED' } },
        spacing: { before: 40, after: 40 },
      }))
      continue
    }

    // Horizontal rule
    if (/^---+$/.test(line.trim())) {
      children.push(new Paragraph({
        children: [new TextRun({ text: '' })],
        border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' } },
        spacing: { before: 200, after: 200 },
      }))
      continue
    }

    // Empty line
    if (!line.trim()) { children.push(new Paragraph({ children: [], spacing: { before: 80 } })); continue }

    // Regular paragraph
    children.push(new Paragraph({ children: parseInline(line), spacing: { before: 80, after: 80 } }))
  }

  // Flush remaining
  flushCode()
  flushTable()

  const doc = new Document({
    numbering: {
      config: [{ reference: 'default-numbering', levels: [{ level: 0, format: 'decimal' as any, text: '%1.', alignment: AlignmentType.START }] }],
    },
    sections: [{
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      headers: {
        default: {
          options: { children: [
            new Paragraph({
              children: [new TextRun({ text: title, size: 16, color: '999999', font: 'Calibri', italics: true })],
              alignment: AlignmentType.RIGHT,
            }),
          ]},
        },
      },
      footers: {
        default: {
          options: { children: [
            new Paragraph({
              children: [new TextRun({ text: 'Generated by ConvoiaAI', size: 14, color: '999999', font: 'Calibri' })],
              alignment: AlignmentType.CENTER,
            }),
          ]},
        },
      },
      children: [
        // Title
        new Paragraph({
          children: [new TextRun({ text: title, bold: true, size: 48, font: 'Calibri', color: '1A1A1A' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 80 },
        }),
        new Paragraph({
          children: [new TextRun({
            text: `Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
            size: 20, color: '888888', font: 'Calibri',
          })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: '' })],
          border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: '7C3AED' } },
          spacing: { after: 300 },
        }),
        ...children,
      ],
    }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${title.replace(/[^a-zA-Z0-9\s-]/g, '').trim().replace(/\s+/g, '-')}.docx`)
}
