/**
 * Client-side document export — PDF via html2pdf.js, DOCX via docx library.
 * Both use dynamic imports so they're only loaded when the user clicks download.
 */

// ── PDF Export ──
export async function exportToPdf(contentElement: HTMLElement, title: string): Promise<void> {
  const html2pdf = (await import('html2pdf.js')).default

  // Clone element and apply print-friendly styles
  const clone = contentElement.cloneNode(true) as HTMLElement
  const wrapper = document.createElement('div')
  wrapper.style.cssText = `
    background: white; color: #1a1a1a; padding: 40px 50px; font-family: 'Georgia', 'Times New Roman', serif;
    font-size: 14px; line-height: 1.8; max-width: 700px; margin: 0 auto;
  `

  // Title page header
  const header = document.createElement('div')
  header.style.cssText = 'text-align: center; margin-bottom: 40px; padding-bottom: 24px; border-bottom: 2px solid #7C3AED;'
  header.innerHTML = `
    <h1 style="font-size: 28px; color: #1a1a1a; margin: 0 0 8px; font-weight: 700;">${title}</h1>
    <p style="font-size: 12px; color: #666; margin: 0;">Generated by ConvoiaAI &bull; ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
  `
  wrapper.appendChild(header)

  // Style overrides for print
  clone.querySelectorAll('*').forEach((el) => {
    const e = el as HTMLElement
    e.style.color = e.style.color || '#1a1a1a'
    e.style.background = 'transparent'
  })
  // Headings
  clone.querySelectorAll('h1, h2, h3').forEach((el) => {
    const e = el as HTMLElement
    e.style.color = '#1a1a1a'
    e.style.borderBottom = el.tagName === 'H1' ? '1px solid #ddd' : 'none'
    e.style.paddingBottom = el.tagName === 'H1' ? '8px' : '0'
    e.style.pageBreakAfter = 'avoid'
  })
  // Code blocks
  clone.querySelectorAll('pre, code').forEach((el) => {
    const e = el as HTMLElement
    e.style.background = '#f5f5f5'
    e.style.color = '#333'
    e.style.border = '1px solid #e0e0e0'
    e.style.borderRadius = '6px'
    e.style.fontFamily = "'Fira Code', 'Consolas', monospace"
    e.style.fontSize = '12px'
    e.style.pageBreakInside = 'avoid'
  })
  // Tables
  clone.querySelectorAll('table').forEach((el) => {
    const e = el as HTMLElement
    e.style.borderCollapse = 'collapse'
    e.style.width = '100%'
    e.style.pageBreakInside = 'avoid'
  })
  clone.querySelectorAll('th, td').forEach((el) => {
    const e = el as HTMLElement
    e.style.border = '1px solid #ddd'
    e.style.padding = '8px 12px'
    e.style.color = '#1a1a1a'
    e.style.background = el.tagName === 'TH' ? '#f0f0f0' : 'transparent'
  })
  // Blockquotes
  clone.querySelectorAll('blockquote').forEach((el) => {
    const e = el as HTMLElement
    e.style.borderLeft = '3px solid #7C3AED'
    e.style.paddingLeft = '16px'
    e.style.color = '#555'
    e.style.fontStyle = 'italic'
  })

  wrapper.appendChild(clone)

  // Footer
  const footer = document.createElement('div')
  footer.style.cssText = 'text-align: center; margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 10px; color: #999;'
  footer.textContent = 'Powered by ConvoiaAI — convoia.com'
  wrapper.appendChild(footer)

  // Generate PDF
  const opt = {
    margin: [15, 15, 20, 15] as [number, number, number, number],
    filename: `${title.replace(/[^a-zA-Z0-9\s-]/g, '').trim().replace(/\s+/g, '-')}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' as const },
    pagebreak: { mode: ['avoid-all', 'css', 'legacy'] },
  }

  await html2pdf().set(opt).from(wrapper).save()
}

// ── DOCX Export ──
export async function exportToDocx(markdownContent: string, title: string): Promise<void> {
  const {
    Document, Packer, Paragraph, TextRun, HeadingLevel,
    AlignmentType, BorderStyle, Table, TableRow, TableCell,
    WidthType, ShadingType,
  } = await import('docx')
  const { saveAs } = await import('file-saver')

  const lines = markdownContent.split('\n')
  const children: any[] = []
  let inCodeBlock = false
  let codeLines: string[] = []
  let inTable = false
  let tableRows: string[][] = []

  function flushCode() {
    if (codeLines.length === 0) return
    children.push(
      new Paragraph({
        children: [new TextRun({
          text: codeLines.join('\n'),
          font: 'Consolas',
          size: 18,
          color: '333333',
        })],
        shading: { type: ShadingType.SOLID, color: 'F5F5F5', fill: 'F5F5F5' },
        spacing: { before: 120, after: 120 },
        border: {
          top: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          left: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          right: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
        },
      })
    )
    codeLines = []
  }

  function flushTable() {
    if (tableRows.length === 0) return
    const rows = tableRows.map((cells, rowIdx) =>
      new TableRow({
        children: cells.map(cell =>
          new TableCell({
            children: [new Paragraph({
              children: [new TextRun({ text: cell.trim(), bold: rowIdx === 0, size: 20, font: 'Calibri' })],
              spacing: { before: 40, after: 40 },
            })],
            width: { size: Math.floor(100 / cells.length), type: WidthType.PERCENTAGE },
            shading: rowIdx === 0 ? { type: ShadingType.SOLID, color: 'F0EFFF', fill: 'F0EFFF' } : undefined,
          })
        ),
      })
    )
    children.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }))
    tableRows = []
  }

  // Parse inline bold/italic
  function parseInline(text: string): any[] {
    const runs: any[] = []
    const regex = /(\*\*\*(.+?)\*\*\*|\*\*(.+?)\*\*|\*(.+?)\*|`(.+?)`|([^*`]+))/g
    let match
    while ((match = regex.exec(text)) !== null) {
      if (match[2]) runs.push(new TextRun({ text: match[2], bold: true, italics: true, size: 22, font: 'Calibri' }))
      else if (match[3]) runs.push(new TextRun({ text: match[3], bold: true, size: 22, font: 'Calibri' }))
      else if (match[4]) runs.push(new TextRun({ text: match[4], italics: true, size: 22, font: 'Calibri' }))
      else if (match[5]) runs.push(new TextRun({ text: match[5], font: 'Consolas', size: 20, color: '7C3AED' }))
      else if (match[6]) runs.push(new TextRun({ text: match[6], size: 22, font: 'Calibri' }))
    }
    return runs.length ? runs : [new TextRun({ text, size: 22, font: 'Calibri' })]
  }

  for (const line of lines) {
    // Code block toggle
    if (line.trim().startsWith('```')) {
      if (inCodeBlock) { inCodeBlock = false; flushCode() }
      else { inCodeBlock = true; flushTable() }
      continue
    }
    if (inCodeBlock) { codeLines.push(line); continue }

    // Table rows
    if (line.trim().startsWith('|') && line.trim().endsWith('|')) {
      if (!inTable) inTable = true
      const cells = line.split('|').filter(c => c.trim()).map(c => c.trim())
      // Skip separator rows (|---|---|)
      if (cells.every(c => /^[-:]+$/.test(c))) continue
      tableRows.push(cells)
      continue
    } else if (inTable) {
      inTable = false
      flushTable()
    }

    // Headings
    const h1 = line.match(/^#\s+(.+)/)
    const h2 = line.match(/^##\s+(.+)/)
    const h3 = line.match(/^###\s+(.+)/)
    if (h1) { children.push(new Paragraph({ children: parseInline(h1[1]), heading: HeadingLevel.HEADING_1, spacing: { before: 360, after: 120 } })); continue }
    if (h2) { children.push(new Paragraph({ children: parseInline(h2[1]), heading: HeadingLevel.HEADING_2, spacing: { before: 280, after: 100 } })); continue }
    if (h3) { children.push(new Paragraph({ children: parseInline(h3[1]), heading: HeadingLevel.HEADING_3, spacing: { before: 200, after: 80 } })); continue }

    // Bullet list
    const bullet = line.match(/^\s*[-*]\s+(.+)/)
    if (bullet) { children.push(new Paragraph({ children: parseInline(bullet[1]), bullet: { level: 0 }, spacing: { before: 40, after: 40 } })); continue }

    // Numbered list
    const numbered = line.match(/^\s*\d+\.\s+(.+)/)
    if (numbered) { children.push(new Paragraph({ children: parseInline(numbered[1]), numbering: { reference: 'default-numbering', level: 0 }, spacing: { before: 40, after: 40 } })); continue }

    // Blockquote
    const quote = line.match(/^>\s*(.+)/)
    if (quote) {
      children.push(new Paragraph({
        children: [new TextRun({ text: quote[1], italics: true, size: 22, color: '555555', font: 'Calibri' })],
        indent: { left: 720 },
        border: { left: { style: BorderStyle.SINGLE, size: 6, color: '7C3AED' } },
        spacing: { before: 40, after: 40 },
      }))
      continue
    }

    // Horizontal rule
    if (/^---+$/.test(line.trim())) {
      children.push(new Paragraph({
        children: [new TextRun({ text: '' })],
        border: { bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' } },
        spacing: { before: 200, after: 200 },
      }))
      continue
    }

    // Empty line
    if (!line.trim()) { children.push(new Paragraph({ children: [], spacing: { before: 80 } })); continue }

    // Regular paragraph
    children.push(new Paragraph({ children: parseInline(line), spacing: { before: 80, after: 80 } }))
  }

  // Flush remaining
  flushCode()
  flushTable()

  const doc = new Document({
    numbering: {
      config: [{ reference: 'default-numbering', levels: [{ level: 0, format: 'decimal' as any, text: '%1.', alignment: AlignmentType.START }] }],
    },
    sections: [{
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      headers: {
        default: {
          options: { children: [
            new Paragraph({
              children: [new TextRun({ text: title, size: 16, color: '999999', font: 'Calibri', italics: true })],
              alignment: AlignmentType.RIGHT,
            }),
          ]},
        },
      },
      footers: {
        default: {
          options: { children: [
            new Paragraph({
              children: [new TextRun({ text: 'Generated by ConvoiaAI', size: 14, color: '999999', font: 'Calibri' })],
              alignment: AlignmentType.CENTER,
            }),
          ]},
        },
      },
      children: [
        // Title
        new Paragraph({
          children: [new TextRun({ text: title, bold: true, size: 48, font: 'Calibri', color: '1A1A1A' })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 80 },
        }),
        new Paragraph({
          children: [new TextRun({
            text: `Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
            size: 20, color: '888888', font: 'Calibri',
          })],
          alignment: AlignmentType.CENTER,
          spacing: { after: 400 },
        }),
        new Paragraph({
          children: [new TextRun({ text: '' })],
          border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: '7C3AED' } },
          spacing: { after: 300 },
        }),
        ...children,
      ],
    }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${title.replace(/[^a-zA-Z0-9\s-]/g, '').trim().replace(/\s+/g, '-')}.docx`)
}
