#!/usr/bin/env python3
"""
PDF Generator for ConvoiaAI.
Reads JSON from stdin, writes PDF to argv[1].
"""
import sys
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, ListFlowable, ListItem
from reportlab.lib.enums import TA_CENTER


def main():
    output_path = sys.argv[1]
    data = json.load(sys.stdin)

    doc = SimpleDocTemplate(
        output_path, pagesize=letter,
        topMargin=0.75 * inch, bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch, rightMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    purple = HexColor('#7C3AED')
    dark = HexColor('#1a1a2e')

    styles.add(ParagraphStyle('DocTitle', parent=styles['Title'],
                              fontSize=22, textColor=purple, spaceAfter=6, alignment=TA_CENTER))
    styles.add(ParagraphStyle('DocSubtitle', parent=styles['Normal'],
                              fontSize=12, textColor=HexColor('#666666'), spaceAfter=30, alignment=TA_CENTER))
    styles.add(ParagraphStyle('SectionHead', parent=styles['Heading1'],
                              fontSize=14, textColor=dark, spaceBefore=20, spaceAfter=10))
    styles.add(ParagraphStyle('BodyText2', parent=styles['Normal'],
                              fontSize=10, leading=15, spaceAfter=10, textColor=HexColor('#333333')))
    styles.add(ParagraphStyle('Footer', parent=styles['Normal'],
                              fontSize=8, textColor=HexColor('#999999'), alignment=TA_CENTER))

    elements = []
    elements.append(Paragraph(data.get('title', 'Document'), styles['DocTitle']))
    if data.get('subtitle'):
        elements.append(Paragraph(data['subtitle'], styles['DocSubtitle']))
    elements.append(Spacer(1, 12))

    for section in data.get('sections', []):
        sec_type = section.get('type', 'text')
        if section.get('heading'):
            elements.append(Paragraph(section['heading'], styles['SectionHead']))

        if sec_type == 'text':
            content = section.get('content', '')
            for para in content.split('\n'):
                if para.strip():
                    elements.append(Paragraph(para.strip(), styles['BodyText2']))

        elif sec_type == 'table':
            headers = section.get('headers', [])
            rows = section.get('rows', [])
            table_data = [headers] + rows
            t = Table(table_data, repeatRows=1)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), purple),
                ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#FFFFFF')),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 1), (-1, -1), 9),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#DDDDDD')),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [HexColor('#FFFFFF'), HexColor('#F8F8FF')]),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('LEFTPADDING', (0, 0), (-1, -1), 8),
                ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 12))

        elif sec_type == 'list':
            items = section.get('items', [])
            list_items = [ListItem(Paragraph(item, styles['BodyText2'])) for item in items]
            elements.append(ListFlowable(list_items, bulletType='bullet', start='circle'))
            elements.append(Spacer(1, 8))

    elements.append(Spacer(1, 30))
    elements.append(Paragraph(data.get('footer', 'Generated by ConvoiaAI'), styles['Footer']))

    doc.build(elements)
    print(json.dumps({'success': True, 'path': output_path}))


if __name__ == '__main__':
    main()
