#!/usr/bin/env python3
"""DOCX Generator for ConvoiaAI. JSON in via stdin, DOCX written to argv[1]."""
import sys
import json
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH


def main():
    output_path = sys.argv[1]
    data = json.load(sys.stdin)

    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)
    style.font.color.rgb = RGBColor(0x33, 0x33, 0x33)

    title = doc.add_heading(data.get('title', 'Document'), level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x7C, 0x3A, 0xED)

    if data.get('subtitle'):
        sub = doc.add_paragraph(data['subtitle'])
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in sub.runs:
            run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
            run.font.size = Pt(12)

    if data.get('date'):
        date_p = doc.add_paragraph(data['date'])
        date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in date_p.runs:
            run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
            run.font.size = Pt(10)

    doc.add_paragraph()

    for section in data.get('sections', []):
        sec_type = section.get('type', 'text')
        level = section.get('level', 1)
        if section.get('heading'):
            doc.add_heading(section['heading'], level=min(level, 3))

        if sec_type == 'text':
            for para in section.get('content', '').split('\n'):
                if para.strip():
                    doc.add_paragraph(para.strip())

        elif sec_type == 'table':
            headers = section.get('headers', [])
            rows = section.get('rows', [])
            table = doc.add_table(rows=1 + len(rows), cols=len(headers))
            table.style = 'Light Grid Accent 1'
            for i, header in enumerate(headers):
                cell = table.rows[0].cells[i]
                cell.text = str(header)
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True
                        run.font.size = Pt(10)
            for r, row in enumerate(rows):
                for c, value in enumerate(row):
                    if c < len(headers):
                        table.rows[r + 1].cells[c].text = str(value)
            doc.add_paragraph()

        elif sec_type == 'list':
            ordered = section.get('ordered', False)
            style_name = 'List Number' if ordered else 'List Bullet'
            for item in section.get('items', []):
                doc.add_paragraph(item, style=style_name)

    doc.add_paragraph()
    footer_p = doc.add_paragraph(data.get('footer', 'Generated by ConvoiaAI'))
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_p.runs:
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        run.font.size = Pt(8)

    doc.save(output_path)
    print(json.dumps({'success': True, 'path': output_path}))


if __name__ == '__main__':
    main()
