/**
 * Format-specific prompts that make the AI output structured JSON.
 *
 * Why JSON and not code: asking the model to output Python/Node
 * code is unsafe (arbitrary execution) and unreliable (syntax
 * errors, missing imports). Content-as-data keeps file generation
 * deterministic on our side.
 */

export function getPdfPrompt(userRequest: string): string {
  return `The user wants a PDF document. Generate the content as structured JSON.

USER REQUEST: ${userRequest}

Respond with ONLY valid JSON (no markdown, no backticks, no explanation). Use this exact structure:

{
  "title": "Document Title",
  "subtitle": "Optional subtitle",
  "author": "ConvoiaAI",
  "sections": [
    {
      "heading": "Section Heading",
      "content": "Paragraph text. Can be multiple sentences. Use \\n for line breaks within a paragraph.",
      "type": "text"
    },
    {
      "heading": "Data Section",
      "type": "table",
      "headers": ["Column 1", "Column 2", "Column 3"],
      "rows": [
        ["Row 1 data", "Value", "Value"],
        ["Row 2 data", "Value", "Value"]
      ]
    },
    {
      "type": "list",
      "heading": "Key Points",
      "items": ["First point", "Second point", "Third point"]
    }
  ],
  "footer": "Generated by ConvoiaAI"
}

Rules:
- Include 3-8 sections with real, useful content based on the user's request
- Use actual data, analysis, and insights — not placeholder text
- Tables should have real data if the request implies data
- Keep section content focused and professional
- The document should be genuinely useful if printed`;
}

export function getDocxPrompt(userRequest: string): string {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `The user wants a Word document. Generate the content as structured JSON.

USER REQUEST: ${userRequest}

Respond with ONLY valid JSON (no markdown, no backticks, no explanation). Use this exact structure:

{
  "title": "Document Title",
  "subtitle": "Optional subtitle",
  "author": "ConvoiaAI",
  "date": "${dateStr}",
  "sections": [
    {
      "heading": "Section Heading",
      "level": 1,
      "content": "Paragraph text with real content.",
      "type": "text"
    },
    {
      "heading": "Subsection",
      "level": 2,
      "content": "More detailed content.",
      "type": "text"
    },
    {
      "type": "table",
      "heading": "Comparison",
      "headers": ["Feature", "Option A", "Option B"],
      "rows": [["Feature 1", "Yes", "No"]]
    },
    {
      "type": "list",
      "heading": "Recommendations",
      "ordered": false,
      "items": ["First recommendation", "Second recommendation"]
    }
  ],
  "footer": "Generated by ConvoiaAI"
}

Rules:
- Include 4-10 sections with real, substantive content
- Use heading levels 1 and 2 for hierarchy
- Include at least one table or list if appropriate for the request
- Write professional, well-structured prose
- The document should be complete and ready to use`;
}

export function getPptxPrompt(userRequest: string): string {
  return `The user wants a PowerPoint presentation. Generate the content as structured JSON.

USER REQUEST: ${userRequest}

Respond with ONLY valid JSON (no markdown, no backticks, no explanation). Use this exact structure:

{
  "title": "Presentation Title",
  "subtitle": "Subtitle or Author",
  "theme": {
    "primaryColor": "#7C3AED",
    "secondaryColor": "#1E1B4B",
    "accentColor": "#F59E0B"
  },
  "slides": [
    { "type": "title", "title": "Presentation Title", "subtitle": "Prepared by ConvoiaAI" },
    {
      "type": "content",
      "title": "Slide Title",
      "bullets": ["First bullet with real content", "Second bullet with data or insight", "Third point"],
      "notes": "Speaker notes for this slide"
    },
    {
      "type": "two_column",
      "title": "Comparison",
      "left_title": "Option A",
      "left_bullets": ["Point 1", "Point 2"],
      "right_title": "Option B",
      "right_bullets": ["Point 1", "Point 2"]
    },
    {
      "type": "table",
      "title": "Data Overview",
      "headers": ["Metric", "Value", "Change"],
      "rows": [["Revenue", "$1.2M", "+15%"]]
    },
    { "type": "content", "title": "Key Takeaways", "bullets": ["Summary point 1", "Summary point 2"] }
  ]
}

Rules:
- Create 6-12 slides with real, substantive content
- Start with a title slide, end with takeaways or next steps
- Each slide should have 3-5 bullet points maximum
- Include speaker notes for key slides
- Use data, examples, and specific insights — not generic placeholders
- The presentation should be ready to deliver`;
}

export function getXlsxPrompt(userRequest: string): string {
  return `The user wants an Excel spreadsheet. Generate the content as structured JSON.

USER REQUEST: ${userRequest}

Respond with ONLY valid JSON (no markdown, no backticks, no explanation). Use this exact structure:

{
  "title": "Spreadsheet Title",
  "sheets": [
    {
      "name": "Sheet Name",
      "headers": ["Column A", "Column B", "Column C", "Column D"],
      "rows": [
        ["Row 1 data", 100, 200, "=B2+C2"],
        ["Row 2 data", 150, 250, "=B3+C3"]
      ],
      "columnWidths": [25, 15, 15, 15]
    }
  ],
  "formulas_note": "Use Excel formula syntax (=SUM, =AVERAGE, =IF, etc.) in cell values"
}

Rules:
- Create 1-3 sheets as appropriate
- Use real data and formulas based on the user's request
- Include SUM/AVERAGE/COUNT formulas where appropriate
- Set reasonable column widths
- Include 10-50 rows of realistic data
- The spreadsheet should be immediately useful`;
}

export function getFilePrompt(format: 'pdf' | 'docx' | 'pptx' | 'xlsx', userRequest: string): string {
  switch (format) {
    case 'pdf': return getPdfPrompt(userRequest);
    case 'docx': return getDocxPrompt(userRequest);
    case 'pptx': return getPptxPrompt(userRequest);
    case 'xlsx': return getXlsxPrompt(userRequest);
  }
}
