export const TOKEN_PACKAGES = [
  {
    id: 'basic',
    name: 'Basic',
    tokens: 500000,
    price: 1.00,
    pricePerMillion: 2.00,
    description: '~1,000 messages',
    savings: null as string | null,
    popular: false,
    color: '#6B7280',
    icon: '⚡',
  },
  {
    id: 'standard',
    name: 'Standard',
    tokens: 1000000,
    price: 2.00,
    pricePerMillion: 2.00,
    description: '~2,000 messages',
    savings: null as string | null,
    popular: false,
    color: '#3B82F6',
    icon: '🚀',
  },
  {
    id: 'popular',
    name: 'Popular',
    tokens: 5000000,
    price: 8.00,
    pricePerMillion: 1.60,
    description: '~10,000 messages',
    savings: 'Save 20%',
    popular: true,
    color: '#7C3AED',
    icon: '⭐',
  },
  {
    id: 'power',
    name: 'Power',
    tokens: 10000000,
    price: 14.00,
    pricePerMillion: 1.40,
    description: '~20,000 messages',
    savings: 'Save 30%',
    popular: false,
    color: '#6D28D9',
    icon: '💎',
  },
  {
    id: 'pro',
    name: 'Pro',
    tokens: 25000000,
    price: 30.00,
    pricePerMillion: 1.20,
    description: '~50,000 messages',
    savings: 'Save 40%',
    popular: false,
    color: '#4F46E5',
    icon: '🔥',
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tokens: 50000000,
    price: 55.00,
    pricePerMillion: 1.10,
    description: '~100,000 messages',
    savings: 'Save 45%',
    popular: false,
    color: '#1D4ED8',
    icon: '🏢',
  },
] as const;

export type TokenPackage = (typeof TOKEN_PACKAGES)[number];
